---
  title: "Main Research Tests"
---
  
---
  title: "Portfolio Returns"
---
  
```{r prior_code, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
packages <- c("tidyverse", "kableExtra", "knitr", "tidyquant")

for (package in packages) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package, repos="http://cran.us.r-project.org")
  }
  library(package, character.only=T)
}

options("scipen"=99)

options("digits"=3)

data_import <- function(x, na = "") {
  df <- read.csv(x, check.names = FALSE, na.strings = na)
  assign(substr(x, 6, nchar(x)-4), df, envir = .GlobalEnv)
  return(NULL)
}

filenames <- list.files("Data/", pattern = "*.csv", full.names = TRUE)

sapply(filenames, data_import, na = c("", "NA", "#N/A", "#N/A Invalid Security"))

price <- price[,colSums(is.na(price))<nrow(price)]

mcap <- mcap[, colnames(price)]

price[,-1] <- sapply(price[, -1],  as.numeric)
mcap[,-1] <- sapply(mcap[, -1], as.numeric)

price <- xts(price[,-1], order.by = ymd(price$Date))
mcap <- xts(mcap[,-1], order.by = ymd(mcap$Date))
jse <- xts(jse[,"JALSH Index"], order.by = ymd(jse[,1]))
rfr <- xts(rfr[,2], order.by = ymd(rfr$Date))

price <- price["2000/2019"]
mcap <- mcap["2000/2019"]
jse <- jse["2000/2019"]
rfr <- rfr["2000/2019"]

price <- price[endpoints(price)]
mcap <- mcap[index(price)]
jse <- jse[index(price)]
rfr <- rfr[index(price)] / 1200

returns <- diff(log(price))
jalsh <- diff(log(jse))

# Top 100 shares 

mcap100 <- t(apply(-mcap, 1, rank, na.last = "keep", ties.method = "first"))

mcap100_mask <- ifelse(mcap100 <= 100,1,NA)

mcap <- mcap * mcap100_mask

returns <- returns * mcap100_mask

vol <- rollapply(data = returns, width = 12, FUN = sd, fill = NA)
volAnn <- vol[endpoints(vol, on = "years")] * sqrt(12)

yrs <- year(index(volAnn))[-1]

for (yr in yrs) {
  mon <- as.character(yr)
  temp <- coredata(volAnn[mon])
  vol[mon, ] <- rbind(temp, temp[rep(1, 11), ])
}

vol100 <- t(apply(-vol, 1, rank, na.last = "keep", ties.method = "first"))

high_vol <- ifelse(vol100 <= 20, 1, NA)
vol_2 <- ifelse(vol100 > 20 & vol100 <= 40, 1, NA)
vol_3 <- ifelse(vol100 > 40 & vol100 <= 60, 1, NA)
vol_4 <- ifelse(vol100 > 60 & vol100 <= 80, 1, NA)
low_vol <- ifelse(vol100 > 80 & vol100 <= 100, 1, NA)

high_vol <- ifelse(vol100 <= quantile(vol100, 0.2, na.rm = TRUE), 1, NA)
vol_2 <- ifelse(vol100 > quantile(vol100, 0.2, na.rm = TRUE) & vol100 <= quantile(vol100, 0.4, 
                                                                                  na.rm = TRUE), 1, NA)
vol_3 <- ifelse(vol100 > quantile(vol100, 0.4, na.rm = TRUE) & vol100 <= quantile(vol100, 0.6, 
                                                                                  na.rm = TRUE), 1, NA)
vol_4 <- ifelse(vol100 > quantile(vol100, 0.6, na.rm = TRUE) & vol100 <= quantile(vol100, 0.8, 
                                                                                  na.rm = TRUE), 1, NA)
low_vol <- ifelse(vol100 > quantile(vol100, 0.8, 
                                    na.rm = TRUE), 1, NA)

portfolio <- data.frame(high = rowMeans(returns * high_vol, na.rm = T),
                        port2 = rowMeans(returns * vol_2, na.rm = T),
                        port3 = rowMeans(returns * vol_3, na.rm = T),
                        port4 = rowMeans(returns * vol_4, na.rm = T),
                        low = rowMeans(returns * low_vol, na.rm = T),
                        row.names = index(returns))
portfolio[1:12,] <- 0

r.xts <- xts(portfolio, order.by = index(returns))[-c(1:11),]
c.xts <- cumprod(1+r.xts)
port_ret <- data.frame(dates = index(-c.xts), c.xts)
```



```{r }
jalsh <- jalsh[index(r.xts)]
rfr <- rfr[index(r.xts)]
# betas <- lm(r.xts ~ jalsh - rfr)
```



```{r blank}
```

